# Generated by Django 4.0 on 2022-02-24 22:51

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_type', models.CharField(choices=[('1', 'legal'), ('2', 'physical')], max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('sponsor_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('choice_money', models.CharField(choices=[('1', '1_000_000'), ('2', '5_000_000'), ('3', '7_000_000'), ('4', '10_000_000'), ('5', '30_000_000')], max_length=100, null=True)),
                ('enter_money', models.PositiveIntegerField(null=True)),
                ('company_name', models.CharField(max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsors',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='UniversityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('student_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('student_type', models.CharField(choices=[('1', 'Bachelor'), ('2', 'Master'), ('3', 'Phd')], max_length=100)),
                ('contract', models.PositiveIntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.universitymodel')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='SponsorshipModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsorship_money', models.PositiveIntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to='main.sponsormodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentships', to='main.studentmodel')),
            ],
            options={
                'verbose_name': ['Sponsorship'],
                'verbose_name_plural': ['Sponsorships'],
                'ordering': ['-created_date'],
            },
        ),
    ]
