# Generated by Django 4.0 on 2022-02-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_sponsormodel_person_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsormodel',
            name='sponsor_number',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
