# Generated by Django 4.0 on 2022-02-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_sponsormodel_sponsor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsormodel',
            name='choice_money',
            field=models.CharField(choices=[('1_000_000', '1_000_000'), ('5_000_000', '5_000_000'), ('7_000_000', '7_000_000'), ('10_000_000', '10_000_000'), ('30_000_000', '30_000_000')], max_length=100, null=True),
        ),
    ]
