# Generated by Django 4.0 on 2022-02-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_sponsormodel_pay_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='student_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
