# Generated by Django 4.0 on 2022-02-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_studentmodel_student_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='student_type',
            field=models.CharField(choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Phd', 'Phd')], max_length=100),
        ),
    ]
